#!/bin/sh
# add logic from the upstream emacsclient.desktop script which supports
# spawning a new frame when launched with no arguments but only do this
# when we are launched from the desktop file which we can detect via the
# GIO_LAUNCHED_DESKTOP_FILE environment variable and associated
# GIO_LAUNCHED_DESKTOP_FILE_PID
if [ -n "$GIO_LAUNCHED_DESKTOP_FILE" ] && [ "$$" -eq "$GIO_LAUNCHED_DESKTOP_FILE_PID" ]; then
  # the following is the logic from the upstream emacsclient.desktop file
  if [ -n "$*" ]; then
    exec $SNAP/usr/bin/emacsclient --alternate-editor= --reuse-frame "$@"
  else
    exec $SNAP/usr/bin/emacsclient --alternate-editor= --create-frame
  fi
else
  exec $SNAP/usr/bin/emacsclient "$@"
fi
