#!/bin/sh

if [ "$SNAP_ARCH" = "amd64" ]; then
  ARCH="x86_64-linux-gnu"
elif [ "$SNAP_ARCH" = "armhf" ]; then
  ARCH="arm-linux-gnueabihf"
elif [ "$SNAP_ARCH" = "arm64" ]; then
  ARCH="aarch64-linux-gnu"
else
  ARCH="$SNAP_ARCH-linux-gnu"
fi

GDK_CACHE_DIR="$SNAP_USER_COMMON/.cache"
[ ! -d "$GDK_CACHE_DIR" ] && mkdir -p "$GDK_CACHE_DIR"

# Gdk-pixbuf loaders
export GDK_PIXBUF_MODULE_FILE="$GDK_CACHE_DIR/gdk-pixbuf-loaders.cache"
export GDK_PIXBUF_MODULEDIR="$SNAP/usr/lib/$ARCH/gdk-pixbuf-2.0/2.10.0/loaders"
if [ -f "$SNAP/usr/lib/$ARCH/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders" ]; then
  "$SNAP/usr/lib/$ARCH/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders" > "$GDK_PIXBUF_MODULE_FILE"
fi

# Gio modules
export GIO_MODULE_DIR="$SNAP/usr/lib/$ARCH/gio/modules"

# setup fontconfig cache to avoid the system cache
FONTCONFIG_CACHE_DIR="$SNAP_USER_COMMON/.cache/fontconfig"
[ ! -d "$FONTCONFIG_CACHE_DIR" ] && mkdir -p "$FONTCONFIG_CACHE_DIR"

export FONTCONFIG_FILE="$SNAP_USER_COMMON/fonts.conf"
[ ! -f "$FONTCONFIG_FILE" ] && sed "s|/var|$SNAP_USER_COMMON|" "$SNAP/etc/fonts/fonts.conf" > "$FONTCONFIG_FILE"

exec "$@"
