#!/bin/sh

if [ "$SNAP_ARCH" = "amd64" ]; then
  ARCH="x86_64-linux-gnu"
elif [ "$SNAP_ARCH" = "armhf" ]; then
  ARCH="arm-linux-gnueabihf"
elif [ "$SNAP_ARCH" = "arm64" ]; then
  ARCH="aarch64-linux-gnu"
else
  ARCH="$SNAP_ARCH-linux-gnu"
fi

GDK_CACHE_DIR="$SNAP_USER_COMMON/.cache"
[ ! -d "$GDK_CACHE_DIR" ] && mkdir -p "$GDK_CACHE_DIR"

# Gdk-pixbuf loaders
export GDK_PIXBUF_MODULE_FILE="$GDK_CACHE_DIR/gdk-pixbuf-loaders.cache"
export GDK_PIXBUF_MODULEDIR="$SNAP/usr/lib/$ARCH/gdk-pixbuf-2.0/2.10.0/loaders"
if [ -f "$SNAP/usr/lib/$ARCH/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders" ]; then
  "$SNAP/usr/lib/$ARCH/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders" > "$GDK_PIXBUF_MODULE_FILE"
fi

# Gio modules
export GIO_MODULE_DIR="$SNAP/usr/lib/$ARCH/gio/modules"

# setup fontconfig cache to avoid the system cache
FONTCONFIG_CACHE_DIR="$SNAP_USER_COMMON/.cache/fontconfig"
[ ! -d "$FONTCONFIG_CACHE_DIR" ] && mkdir -p "$FONTCONFIG_CACHE_DIR"

# create a fontconfig file which specifies only our cache
export FONTCONFIG_FILE="$SNAP_USER_COMMON/fonts.conf"
# always recreate this to ensure we overwrite an old one which may have
# come from a different base snap version etc in a previous release of the
# emacs snap
cp "$SNAP/etc/fonts/fonts.conf" "$FONTCONFIG_FILE"
# there are usually multiple cachedir's listed - one under /var, one in
# home etc - we only want one and we want it to be specific for the snap so
# we don't encounter cache files created by a different version of
# fontconfig - so replace *all* with ours
sed -i "s|<cachedir.*/cachedir>|<cachedir>$FONTCONFIG_CACHE_DIR</cachedir>|" "$FONTCONFIG_FILE"

# native comp needs to find as etc and this comes from within the snap
# itself
export PATH="$PATH:/snap/emacs/current/usr/bin"

exec "$@"
