name: emacs
version: '27+git'
summary: GNU Emacs is the extensible self-documenting text editor
description: |
  Emacs is the extensible, customizable, self-documenting real-time
  display editor.

  Features include:
    * Content-aware editing modes, including syntax coloring, for many file types.
    * Complete built-in documentation, including a tutorial for new users.
    * Full Unicode support for nearly all human scripts.
    * Highly customizable, using Emacs Lisp code or a graphical interface.
    * An entire ecosystem of functionality beyond text editing, including a project
      planner, mail and news reader, debugger interface, calendar, and more.
    * A packaging system for downloading and installing extensions.

  This snap is built via the build.snapcraft.io service from the
  snapcraft.yaml definition at https://github.com/alexmurray/emacs-snap to
  ensure source and build transparency.

base: core18
grade: stable
confinement: classic
license: GPL-3.0+

apps:
  emacs:
    command: usr/bin/emacs
    desktop: usr/share/applications/emacs.desktop
  emacsclient:
    command: usr/bin/emacsclient
  ctags:
    command: usr/bin/ctags
  ebrowse:
    command: usr/bin/ebrowse
  etags:
    command: usr/bin/etags

parts:
  emacs-git:
    plugin: autotools
    source: https://github.com/emacs-mirror/emacs.git
    source-type: git
    source-depth: 1
    source-branch: master
    configflags: ["--prefix=/snap/emacs-git/current/usr", "--with-xwidgets", "--with-x-toolkit=gtk3", "--without-xaw3d"]
    organize:
      snap/emacs-git/current/usr: usr
    build-packages:
      - autoconf
      - automake
      - bsd-mailx
      - dbus-x11
      - debhelper
      - dpkg-dev
      - gnupg-agent
      - imagemagick
      - libacl1-dev
      - libasound2-dev
      - libdbus-1-dev
      - libgif-dev
      - libgnutls28-dev
      - libgpm-dev
      - libgtk-3-dev
      - libjpeg-dev
      - liblockfile-dev
      - libm17n-dev
      - libmagick++-6.q16-dev
      - libncurses5-dev
      - liboss4-salsa2
      - libotf-dev
      - libpng-dev
      - librsvg2-dev
      - libselinux1-dev
      - libsystemd-dev
      - libtiff-dev
      - libxaw7-dev
      - libxml2-dev
      - procps
      - quilt
      - sharutils
      - texinfo
      - xaw3dg-dev
      - zlib1g-dev
      - libjansson-dev
      - libwebkit2gtk-4.0-dev
    stage-packages:
      - libasound2
      - libatk-bridge2.0-0
      - libatspi2.0-0
      - libcairo-gobject2
      - libcairo2
      - libcroco3
      - libdatrie1
      - libepoxy0
      - libfftw3-double3
      - libfontconfig1
      - libfreetype6
      - libgdk-pixbuf2.0-0
      - libgif7
      - libgomp1
      - libgpm2
      - libgraphite2-3
      - libgtk-3-0
      - libharfbuzz0b
      - libice6
      - libicu60
      - libjbig0
      - libjpeg-turbo8
      - liblcms2-2
      - liblockfile1
      - liblqr-1-0
      - libltdl7
      - libm17n-0
      - libmagickcore-6.q16-3
      - libmagickwand-6.q16-3
      - liboss4-salsa-asound2
      - libotf0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpng16-16
      - librsvg2-2
      - libsm6
      - libthai0
      - libtiff5
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libwayland-egl1-mesa
      - libx11-6
      - libx11-xcb1
      - libxau6
      - libxau6-dbg
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxcomposite1
      - libxcomposite1-dbg
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxext6-dbg
      - libxfixes3
      - libxft2
      - libxi6
      - libxinerama1
      - libxinerama1-dbg
      - libxkbcommon0
      - libxml2
      - libxpm4
      - libxrandr2
      - libxrender1
      - libbrotli1
      - libenchant1c2a
      - libgl1
      - libglx0
      - libgstreamer-gl1.0-0
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - libgudev-1.0-0
      - libharfbuzz-icu0
      - libhyphen0
      - libjansson4
      - libjavascriptcoregtk-4.0-18
      - libnotify4
      - liborc-0.4-0
      - libsecret-1-0
      - libwebkit2gtk-4.0-37
      - libwebpdemux2
      - libwoff1
      - libxslt1.1
    override-prime: |
      set -eu
      snapcraftctl prime
      # Fix-up application icon lookup
      sed -i.bak -e 's|^Icon=.*|Icon=usr/share/icons/hicolor/scalable/apps/emacs.svg|g' usr/share/applications/emacs.desktop
