name: emacs
version: "27.1"
summary: GNU Emacs is the extensible self-documenting text editor
description: |
  Emacs is the extensible, customizable, self-documenting real-time
  display editor.

  Features include:
    * Content-aware editing modes, including syntax coloring, for many file types.
    * Complete built-in documentation, including a tutorial for new users.
    * Full Unicode support for nearly all human scripts.
    * Highly customizable, using Emacs Lisp code or a graphical interface.
    * An entire ecosystem of functionality beyond text editing, including a project
      planner, mail and news reader, debugger interface, calendar, and more.
    * A packaging system for downloading and installing extensions.

  This snap is built via the build.snapcraft.io service from the
  snapcraft.yaml definition at https://github.com/alexmurray/emacs-snap to
  ensure source and build transparency.

base: core18
grade: stable
confinement: classic
license: GPL-3.0+

apps:
  emacs:
    command-chain:
      - setup-env
    command: usr/bin/emacs
    desktop: usr/share/applications/emacs.desktop
    # Required until Snapcraft 3.9
    # https://github.com/snapcore/snapcraft/pull/2686
    adapter: full
  emacsclient:
    command: usr/bin/emacsclient
  ctags:
    command: usr/bin/ctags
  ebrowse:
    command: usr/bin/ebrowse
  etags:
    command: usr/bin/etags

parts:
  emacs:
    plugin: autotools
    source: https://mirrors.ocf.berkeley.edu/gnu/emacs/emacs-27.1.tar.xz
    source-checksum: sha512/dfb26531d2c19cf9fb56505f03d799654b45e5f9528e777900e8280ed2c1d21e04c52f510528e31e015977c471ae63164cedee6174b7439ebcf479a21fc18064
    configflags: ["--prefix=/snap/emacs/current/usr", "--with-xwidgets", "--with-x-toolkit=gtk3", "--without-xaw3d", "--with-modules", "--with-cairo"]
    organize:
      snap/emacs/current/usr: usr
    build-packages:
      - autoconf
      - automake
      - bsd-mailx
      - dbus-x11
      - debhelper
      - dpkg-dev
      - libacl1-dev
      - libasound2-dev
      - libdbus-1-dev
      - libgif-dev
      - libgnutls28-dev
      - libgpm-dev
      - libgtk-3-dev
      - libjansson-dev
      - libjpeg-dev
      - liblcms2-dev
      - liblockfile-dev
      - libm17n-dev
      - libncurses5-dev
      - liboss4-salsa2
      - libotf-dev
      - libpng-dev
      - librsvg2-dev
      - libselinux1-dev
      - libsystemd-dev
      - libtiff-dev
      - libwebkit2gtk-4.0-dev
      - libxml2-dev
      - libxpm-dev
      - procps
      - quilt
      - sharutils
      - texinfo
      - zlib1g-dev
    stage-packages:
      - gvfs
      - language-pack-en-base
      - libasound2
      - libaspell15
      - libasyncns0
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatspi2.0-0
      - libbrotli1
      - libcairo-gobject2
      - libcairo2
      - libcanberra-gtk3-0
      - libcanberra-gtk3-module
      - libcanberra0
      - libcroco3
      - libdatrie1
      - libdb5.3
      - libdrm2
      - libegl1
      - libenchant1c2a
      - libepoxy0
      - libflac8
      - libfontconfig1
      - libfreetype6
      - libgbm1
      - libgdk-pixbuf2.0-0
      - libgif7
      - libgl1
      - libglvnd0
      - libglx0
      - libgpm2
      - libgraphite2-3
      - libgstreamer-gl1.0-0
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - libgtk-3-0
      - libgudev-1.0-0
      - libharfbuzz-icu0
      - libharfbuzz0b
      - libhyphen0
      - libice6
      - libicu60
      - libjansson4
      - libjavascriptcoregtk-4.0-18
      - libjbig0
      - libjpeg-turbo8
      - liblcms2-2
      - liblockfile1
      - libltdl7
      - libm17n-0
      - libnotify4
      - libnss-mdns
      - libnss-myhostname
      - libnss-systemd
      - libogg0
      - liborc-0.4-0
      - libotf0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpng16-16
      - libpulse0
      - librsvg2-2
      - libsasl2-2
      - libsecret-1-0
      - libsm6
      - libsndfile1
      - libsoup2.4-1
      - libssl1.1
      - libstdc++6
      - libtdb1
      - libthai0
      - libtiff5
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libwayland-server0
      - libwebkit2gtk-4.0-37
      - libwebp6
      - libwebpdemux2
      - libwoff1
      - libx11-6
      - libx11-xcb1
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxml2
      - libxpm4
      - libxrandr2
      - libxrender1
      - libxslt1.1
      - libyajl2
    stage:
      - -usr/share/emacs/site-lisp
    build-environment:
      - CFLAGS: "$CFLAGS -O2"
    override-prime: |
      set -eu
      snapcraftctl prime
      # Fix-up application icon lookup
      sed -i.bak -e 's|^Icon=.*|Icon=usr/share/icons/hicolor/scalable/apps/emacs.svg|g' usr/share/applications/emacs.desktop
  site-lisp:
    source: site-lisp
    plugin: dump
    organize:
      '*.el': usr/share/emacs/site-lisp/
  command-chain:
    source: .
    plugin: dump
    stage:
      - setup-env
